# Generated by Django 4.0.3 on 2022-06-11 15:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Films_MCU', '0014_alter_superhero_date_alter_films_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superhero',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 6, 11, 15, 41, 8, 121846, tzinfo=utc)),
        ),
    ]
